#!/usr/bin/env python
"""Summarize SynthTab validation errors from saved evaluation outputs.

This script is intentionally CPU-only: it reads `results/summary.json` and
per-track `.txt` metric files generated by the existing evaluation pipeline.
It does not import the training pipeline and does not load a model.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from statistics import mean, median
from typing import Iterable


METRIC_LINE = re.compile(r"^\s*([A-Za-z0-9_-]+)\s+:\s+([-+0-9.eE]+)\s*$")


@dataclass
class TrackMetrics:
    track_id: str
    multi_pitch_f1: float | None = None
    tablature_f1: float | None = None
    tablature_accuracy: float | None = None
    tablature_tdr: float | None = None
    ref_silence_ratio: float | None = None
    pred_silence_ratio: float | None = None
    non_silent_accuracy: float | None = None

    @property
    def silence_delta(self) -> float | None:
        if self.pred_silence_ratio is None or self.ref_silence_ratio is None:
            return None
        return self.pred_silence_ratio - self.ref_silence_ratio

    @property
    def string_fret_gap(self) -> float | None:
        if self.multi_pitch_f1 is None or self.tablature_f1 is None:
            return None
        return self.multi_pitch_f1 - self.tablature_f1


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def metric_value(section: dict, key: str) -> float | None:
    value = section.get(key)
    return float(value) if isinstance(value, (int, float)) else None


def parse_metric_txt(path: Path) -> dict[str, dict[str, float]]:
    sections: dict[str, dict[str, float]] = {}
    current: str | None = None

    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        stripped = line.strip()
        if stripped.startswith("-----") and stripped.endswith("-----"):
            current = stripped.strip("-").strip()
            sections.setdefault(current, {})
            continue
        if current is None:
            continue
        match = METRIC_LINE.match(line)
        if match:
            key, raw = match.groups()
            sections[current][key] = float(raw)

    return sections


def txt_track_id(results_dir: Path, txt_path: Path) -> str:
    return str(txt_path.relative_to(results_dir).with_suffix(""))


def load_track_metrics(experiment_dir: Path) -> tuple[dict, list[TrackMetrics]]:
    results_dir = experiment_dir / "results"
    summary = load_json(results_dir / "summary.json")
    diagnostics = summary.get("synthtab_val", {}).get("diagnostics", {})
    diagnostic_tracks = {
        track["track_id"]: track
        for track in diagnostics.get("tracks", [])
        if isinstance(track, dict) and isinstance(track.get("track_id"), str)
    }

    tracks: list[TrackMetrics] = []
    for txt_path in sorted(results_dir.rglob("*.txt")):
        sections = parse_metric_txt(txt_path)
        track_id = txt_track_id(results_dir, txt_path)
        diag = diagnostic_tracks.get(track_id, {})
        multi_pitch = sections.get("multi_pitch", {})
        tablature = sections.get("tablature", {})

        tracks.append(
            TrackMetrics(
                track_id=track_id,
                multi_pitch_f1=metric_value(multi_pitch, "f1-score"),
                tablature_f1=metric_value(tablature, "f1-score"),
                tablature_accuracy=metric_value(tablature, "accuracy"),
                tablature_tdr=metric_value(tablature, "tdr"),
                ref_silence_ratio=metric_value(diag, "ref_silence_ratio"),
                pred_silence_ratio=metric_value(diag, "pred_silence_ratio"),
                non_silent_accuracy=metric_value(diag, "non_silent_accuracy"),
            )
        )

    return summary, tracks


def values(tracks: Iterable[TrackMetrics], attr: str) -> list[float]:
    result = []
    for track in tracks:
        value = getattr(track, attr)
        if isinstance(value, (int, float)):
            result.append(float(value))
    return result


def derived_values(tracks: Iterable[TrackMetrics], attr: str) -> list[float]:
    result = []
    for track in tracks:
        value = getattr(track, attr)
        if isinstance(value, (int, float)):
            result.append(float(value))
    return result


def fmt(value: float | None, percent: bool = True) -> str:
    if value is None:
        return "n/a"
    if percent:
        return f"{value * 100:.2f}%"
    return f"{value:.4f}"


def summarize_distribution(name: str, data: list[float]) -> str:
    if not data:
        return f"| {name} | n/a | n/a | n/a | n/a |"
    return f"| {name} | {fmt(mean(data))} | {fmt(median(data))} | {fmt(min(data))} | {fmt(max(data))} |"


def table_tracks(tracks: list[TrackMetrics], title: str) -> list[str]:
    lines = [f"### {title}", "", "| Track | MP F1 | Tab F1 | Gap | Ref silence | Pred silence | Non-silent acc |", "|---|---:|---:|---:|---:|---:|---:|"]
    for track in tracks:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{track.track_id}`",
                    fmt(track.multi_pitch_f1),
                    fmt(track.tablature_f1),
                    fmt(track.string_fret_gap),
                    fmt(track.ref_silence_ratio),
                    fmt(track.pred_silence_ratio),
                    fmt(track.non_silent_accuracy),
                ]
            )
            + " |"
        )
    return lines


def run_report(label: str, experiment_dir: Path) -> list[str]:
    summary, tracks = load_track_metrics(experiment_dir)
    synthtab_val = summary.get("synthtab_val", {})
    diagnostics = synthtab_val.get("diagnostics", {})

    ranked = [track for track in tracks if track.tablature_f1 is not None]
    worst = sorted(ranked, key=lambda track: (track.tablature_f1 or 0.0, track.non_silent_accuracy or 0.0))[:5]
    best = sorted(ranked, key=lambda track: (track.tablature_f1 or 0.0, track.non_silent_accuracy or 0.0), reverse=True)[:5]
    typical = sorted(
        ranked,
        key=lambda track: abs((track.tablature_f1 or 0.0) - median(values(ranked, "tablature_f1"))),
    )[:5]

    lines = [
        f"## {label}",
        "",
        f"- Experiment: `{experiment_dir}`",
        f"- Tracks with per-track metrics: `{len(tracks)}`",
        f"- Aggregate multi-pitch F1: `{fmt(metric_value(synthtab_val.get('multi_pitch', {}), 'f1-score'))}`",
        f"- Aggregate tablature F1: `{fmt(metric_value(synthtab_val.get('tablature', {}), 'f1-score'))}`",
        f"- Aggregate tablature accuracy: `{fmt(metric_value(synthtab_val.get('tablature', {}), 'accuracy'))}`",
        f"- Aggregate non-silent accuracy: `{fmt(metric_value(diagnostics, 'non_silent_accuracy'))}`",
        f"- Aggregate ref/pred silence: `{fmt(metric_value(diagnostics, 'ref_silence_ratio'))}` / `{fmt(metric_value(diagnostics, 'pred_silence_ratio'))}`",
        f"- Collapse to silence: `{diagnostics.get('collapse_to_silence')}`",
        "",
        "| Metric | Mean | Median | Min | Max |",
        "|---|---:|---:|---:|---:|",
        summarize_distribution("per-track multi-pitch F1", values(tracks, "multi_pitch_f1")),
        summarize_distribution("per-track tablature F1", values(tracks, "tablature_f1")),
        summarize_distribution("multi-pitch minus tablature F1", derived_values(tracks, "string_fret_gap")),
        summarize_distribution("ref silence ratio", values(tracks, "ref_silence_ratio")),
        summarize_distribution("pred silence ratio", values(tracks, "pred_silence_ratio")),
        summarize_distribution("pred minus ref silence", derived_values(tracks, "silence_delta")),
        "",
    ]
    lines.extend(table_tracks(worst, "Worst validation tracks by tablature F1"))
    lines.append("")
    lines.extend(table_tracks(typical, "Typical validation tracks by tablature F1"))
    lines.append("")
    lines.extend(table_tracks(best, "Best validation tracks by tablature F1"))
    lines.append("")
    return lines


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("experiments", nargs="+", type=Path)
    parser.add_argument("--label", action="append", default=[])
    args = parser.parse_args()

    labels = args.label or [path.name for path in args.experiments]
    if len(labels) != len(args.experiments):
        raise SystemExit("--label count must match experiment count")

    lines = ["# SynthTab Error Analysis", ""]
    for label, experiment in zip(labels, args.experiments):
        lines.extend(run_report(label, experiment))

    print("\n".join(lines))


if __name__ == "__main__":
    main()
